language: csharp
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
 script:
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe .StorePassword/PasswordTests/bin/Debug/PasswordTests.dll
